sudo: required

services:
  - docker

before_install:
  - docker build -t outrigger/docs .

script:
  - docker run -v $PWD:/documents -v $PWD/build:/site outrigger/docs /bin/sh -c "mkdocs build --clean --site-dir /site"

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./build
  target_branch: gh-pages
  github_token: $GITHUB_TOKEN
  on:
    branch: master